version: '3.4'
services:

  mariadb:
    container_name: mariadb
    image: fabiojanio/mariadb:10.2-alpine
    environment:
      - MYSQL_ROOT_PASSWORD=root
      #- MYSQL_PORT=3306
      #- MYSQL_DATABASE=
      #- MYSQL_USER=
      #- MYSQL_PASSWORD=
      #- CHARACTER_SET_SERVER=utf8
      #- COLLATION_SERVER=utf8_unicode_ci
    volumes:
      - mariadb:/var/lib/mysql
    restart: on-failure
    ports:
      - 3306:3306

  web:
    container_name: web
    image: fabiojanio/php-apache
    volumes:
      - ./projeto:/var/www
      #- ./apache:/etc/apache2/sites-enabled/
    working_dir: /var/www
    depends_on:
      - mariadb
    restart: on-failure
    ports:
      - 80:80

volumes:
  mariadb:
    name: mariadb